services:
  api:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env  # Isso fará a API ler o POSTGRES_SERVER do seu .env
    # A seção 'environment' e 'depends_on' foi removida para não forçar o 'db' local
