"""add scraped data tables

Revision ID: d72211cd3dde
Revises: 4ddd90d57fc9
Create Date: 2026-03-02 21:42:16.089718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd72211cd3dde'
down_revision: Union[str, None] = '4ddd90d57fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_item',
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('urgente', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_item_portal_id'), 'feed_item', ['portal_id'], unique=False)
    op.create_index(op.f('ix_feed_item_tipo'), 'feed_item', ['tipo'], unique=False)
    op.create_index(op.f('ix_feed_item_urgente'), 'feed_item', ['urgente'], unique=False)
    op.create_table('outro',
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outro_portal_id'), 'outro', ['portal_id'], unique=False)
    op.create_index(op.f('ix_outro_tipo'), 'outro', ['tipo'], unique=False)
    op.create_table('pedido',
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_categoria'), 'pedido', ['categoria'], unique=False)
    op.create_index(op.f('ix_pedido_cidade'), 'pedido', ['cidade'], unique=False)
    op.create_index(op.f('ix_pedido_portal_id'), 'pedido', ['portal_id'], unique=False)
    op.create_index(op.f('ix_pedido_status'), 'pedido', ['status'], unique=False)
    op.create_table('pet',
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('especie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('porte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imagem_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_cidade'), 'pet', ['cidade'], unique=False)
    op.create_index(op.f('ix_pet_especie'), 'pet', ['especie'], unique=False)
    op.create_index(op.f('ix_pet_portal_id'), 'pet', ['portal_id'], unique=False)
    op.create_index(op.f('ix_pet_tipo'), 'pet', ['tipo'], unique=False)
    op.create_table('ponto_ajuda',
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('itens', sa.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ponto_ajuda_cidade'), 'ponto_ajuda', ['cidade'], unique=False)
    op.create_index(op.f('ix_ponto_ajuda_portal_id'), 'ponto_ajuda', ['portal_id'], unique=False)
    op.create_index(op.f('ix_ponto_ajuda_tipo'), 'ponto_ajuda', ['tipo'], unique=False)
    op.create_table('voluntario',
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voluntario_categoria'), 'voluntario', ['categoria'], unique=False)
    op.create_index(op.f('ix_voluntario_cidade'), 'voluntario', ['cidade'], unique=False)
    op.create_index(op.f('ix_voluntario_portal_id'), 'voluntario', ['portal_id'], unique=False)
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_index(op.f('ix_voluntario_portal_id'), table_name='voluntario')
    op.drop_index(op.f('ix_voluntario_cidade'), table_name='voluntario')
    op.drop_index(op.f('ix_voluntario_categoria'), table_name='voluntario')
    op.drop_table('voluntario')
    op.drop_index(op.f('ix_ponto_ajuda_tipo'), table_name='ponto_ajuda')
    op.drop_index(op.f('ix_ponto_ajuda_portal_id'), table_name='ponto_ajuda')
    op.drop_index(op.f('ix_ponto_ajuda_cidade'), table_name='ponto_ajuda')
    op.drop_table('ponto_ajuda')
    op.drop_index(op.f('ix_pet_tipo'), table_name='pet')
    op.drop_index(op.f('ix_pet_portal_id'), table_name='pet')
    op.drop_index(op.f('ix_pet_especie'), table_name='pet')
    op.drop_index(op.f('ix_pet_cidade'), table_name='pet')
    op.drop_table('pet')
    op.drop_index(op.f('ix_pedido_status'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_portal_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_cidade'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_categoria'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_outro_tipo'), table_name='outro')
    op.drop_index(op.f('ix_outro_portal_id'), table_name='outro')
    op.drop_table('outro')
    op.drop_index(op.f('ix_feed_item_urgente'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_tipo'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_portal_id'), table_name='feed_item')
    op.drop_table('feed_item')
    # ### end Alembic commands ###
